apps/core/templates/core/urls.py
from django.urls import path

from apps.core import views as c

app_name = 'core'

urlpatterns = [
    path('', c.home, name='home'),
    # path('gallery/', c.GalleryList.as_view(), name='gallery_list'),
    # path('add/', c.GalleryCreate.as_view(), name='gallery_add'),
    # path('gallery/<int:pk>/', c.GalleryDetail.as_view(), name='gallery_detail'),
    path('download/<int:pk>/', c.download, name='download'),
]

core/templates/core/urls.py
from django.urls import path

from gallery.core import views as c

app_name = 'core'

urlpatterns = [
    path('', c.home, name='home'),
    path('gallery/', c.GalleryList.as_view(), name='gallery_list'),
    path('add/', c.GalleryCreate.as_view(), name='gallery_add'),
    path('gallery/<int:pk>/', c.GalleryDetail.as_view(), name='gallery_detail'),
    path('download/<int:pk>/', c.download, name='download'),
]

image_gallery/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

apps/core/models.py
from mimetypes import guess_type

from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em', auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(
        'modificado em', auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True

class Gallery(TimeStampedModel):
    description = models.CharField(
        'descrição',
        max_length=20,
        null=True,
        blank=True
    )
    photo = models.ImageField('foto', upload_to='', null=True, blank=True)
    file = models.FileField('arquivo', upload_to='', null=True, blank=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'foto'
        verbose_name_plural = 'fotos'

    def __str__(self):
        if self.description:
            return self.description
        return str(self.pk)

    @property
    def get_filename(self):
        if self.photo or self.file:
            return self.photo.name or self.file.name

    @property
    def get_type(self):
        if self.photo:
            _mimetypes, _ = guess_type(self.photo.name)
            return _mimetypes
        if self.file:
            _mimetypes, _ = guess_type(self.file.name)
            return _mimetypes

apps/core/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Gallery


class GalleryForm(forms.ModelForm):

    class Meta:
        model = Gallery
        fields = ('photo', 'file', 'description')

    def clean(self):
        self.cleaned_data = super().clean()

        if not self.cleaned_data.get('photo') and not self.cleaned_data.get('file'):
            raise ValidationError('Insira uma foto ou um arquivo.')

        return self.cleaned_data

apps/core/views.py
import requests
from django.http import FileResponse, Http404, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy as r
from django.views.generic import CreateView, DetailView, ListView

from .forms import GalleryForm
from .models import Gallery


def home(request):
    return render(request, 'index.html')


class GalleryList(ListView):
    template_name = 'core/gallery_list.html'
    model = Gallery
    context_object_name = 'gallery'


class GalleryDetail(DetailView):
    template_name = 'core/gallery_detail.html'
    model = Gallery


class GalleryCreate(CreateView):
    template_name = 'core/gallery_form.html'
    model = Gallery
    form_class = GalleryForm
    success_url = r('core:gallery_list')


def download(request, pk):
    obj = Gallery.objects.get(pk=pk)

    file_data = None
    if obj.photo:
        # file_data = obj.photo.path
        file_data = obj.photo.url
    if obj.file:
        # file_data = obj.file.path
        file_data = obj.file.url

    if file_data:
        resp = requests.get(file_data)
        filename = file_data.split('/')[-1]
        response = HttpResponse(resp.content, content_type='image/jpeg')
        # Sem extensão do arquivo.
        response['Content-Disposition'] = f'attachment; filename={filename}'
        return response
    return Http404

apps/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block title %}
    <title>Gallery</title>
    {% endblock title %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/thumbnail-gallery.css' %}" rel="stylesheet">

    {% block css %}
    <style type="text/css">
        body {
            padding-top: 60px;
        }
    </style>
    {% endblock css %}

</head>

<body>
{% include "nav.html" %}

<div class="container">

    {% block content %}

    {% endblock content %}

</div> <!-- /container -->

<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

apps/core/templates/core/gallery_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>

apps/core/templates/core/gallery_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

apps/core/templates/core/gallery_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

apps/core/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<style type="text/css">
    body {
        padding-top: 50px;
        background-image: url('{% static "img/giro-d-italia-bike-race.jpg" %}');
        background-repeat: no-repeat;
        background-size: 100%;
    }
    .jumbotron {
        background: rgba(255,255,255, 0.25);
    }
</style>
{% endblock css %}

{% block content %}

<div class="container jumbotron col-sm-4">
    <h1	><a href="{% url 'core:gallery_list' %}" style="text-decoration:none">Gallery</a></h1>
</div>

{% endblock content %}

apps/core/templates/nav.html
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="current"><a href="{% url 'core:home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                <li><a href="{% url 'core:gallery_list' %}">Galeria</a></li>
                <li><a href="{% url 'core:gallery_add' %}">Adicionar</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
            </ul>
        </div>
    </div>
</div>

core/templates/core/gallery_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>